# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 01:51
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Страница')),
                ('metakey', models.CharField(blank=True, max_length=255, verbose_name='Ключевые слова')),
                ('metadesc', models.CharField(blank=True, max_length=255, verbose_name='Мета описание')),
                ('slug', models.CharField(blank=True, max_length=250, verbose_name='Урл')),
                ('page_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст страницы')),
                ('position', models.SmallIntegerField(verbose_name='Позиция')),
            ],
            options={
                'verbose_name_plural': 'страницы',
                'ordering': ['position'],
                'verbose_name': 'страница',
                'db_table': 'pages',
            },
        ),
    ]
