# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 09:01
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20160220_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, upload_to=master.models.make_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='page_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст страницы'),
        ),
    ]
