# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20160221_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
