# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20160221_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pages',
        ),
    ]
