# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_delete_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='metadesc',
            field=models.CharField(blank=True, max_length=255, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='categories',
            name='metakey',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ключевые слова'),
        ),
    ]
