# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20160317_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_publish',
            field=models.NullBooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='recipe',
            field=models.NullBooleanField(default=None, verbose_name='Рецепт'),
        ),
    ]
