# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_20160326_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='recipe',
            field=models.NullBooleanField(default=0, verbose_name='Рецепт'),
        ),
    ]
