# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_auto_20160326_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_publish',
            field=models.BooleanField(default=1, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='recipe',
            field=models.BooleanField(default=0, verbose_name='Рецепт'),
        ),
    ]
